In [40]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

data = pd.read_csv("/content/drive/Shareddrives/project python/sapm_detection/Youtube_spam.csv")
data

COMMENT_ID                AUTHOR  \
0     LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1     LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2     LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3             z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4             z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
...                                           ...                   ...   
1950  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
1951  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
1952  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
1953  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
1954  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                            DATE  \
0            2013-11-07T06:20:48   
1            2013-11-07T12:37:15   
2            2013-11-08T17:34:21   
3            2013-11-09T08:28:43   
4            2013-11-10T16:05:38   
...                          ...   
1950  2013-07-13T13:27:39.441000   
1951  2013-07-13T13:14:30.021000   
1952  2013-07-13T12:09:31.188000   
1953  2013-07-13T11:17:52.308000   
1954  2013-07-12T22:33:27.916000   

                                                CONTENT  CLASS  
0     Huh, anyway check out this you[tube] channel: ...      1  
1     Hey guys check out my new channel and our firs...      1  
2                just for test I have to say murdev.com      1  
3      me shaking my sexy ass on my channel enjoy ^_^       1  
4               watch?v=vtaRGgvGtWQ   Check this out .      1  
...                                                 ...    ...  
1950  I love this song because we sing it at Camp al...      0  
1951  I love this song for two reasons: 1.it is abou...      0  
1952                                                wow      0  
1953                            Shakira u are so wiredo      0  
1954                         Shakira is the best dancer      0  

[1955 rows x 5 columns]

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1955 entries, 0 to 1954
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  1955 non-null   object
 1   AUTHOR      1955 non-null   object
 2   DATE        1711 non-null   object
 3   CONTENT     1955 non-null   object
 4   CLASS       1955 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 76.5+ KB


In [43]:
print(data.sample(5))

                                       COMMENT_ID             AUTHOR  \
1267  LneaDw26bFs2gfQVXn0iARlUHD77c23Quer_0vQFKR4      Jacob Johnson   
271         z13qe1myote4hhwox04chrdxbv30dhraerc0k    hunter braddock   
173           z12nejhigtr0tdvy504cgfcrhzvycxzin0k  Detroit Red Wings   
628         z125idl4dkrwsdlbj04ccpvbcqjbt3hbbqk0k     Mauro Tricolor   
246           z12aezowoqbjf3sn223hc1xrita3f3oz404    UKz DoleSnacher   

                     DATE                                            CONTENT  \
1267                  NaN  You guys should check out this EXTRAORDINARY w...   
271   2014-11-08T06:36:41  For all of the little kidz out there there is ...   
173   2014-11-06T20:55:09                    http://www.gofundme.com/gvr7xg   
628   2014-10-30T20:43:47  http://minhateca.com.br/mauro-sp2013/Filmes+Se...   
246   2014-11-08T02:18:42                        Remove This video its wank   

      CLASS  
1267      1  
271       0  
173       1  
628       1  
246       0  


In [44]:
data = data[["CONTENT", "CLASS"]]
print(data.sample(5))
data

                                                CONTENT  CLASS
344   everyones back lool this is almost 3 years old...      0
1277  He is good boy!!!<br />I am krean I like to em...      0
1590                  The best world cup song ever!!!!      0
1868                               shakira is the best!      0
1536  Usually guys I would vote people like this dow...      1


CONTENT  CLASS
0     Huh, anyway check out this you[tube] channel: ...      1
1     Hey guys check out my new channel and our firs...      1
2                just for test I have to say murdev.com      1
3      me shaking my sexy ass on my channel enjoy ^_^       1
4               watch?v=vtaRGgvGtWQ   Check this out .      1
...                                                 ...    ...
1950  I love this song because we sing it at Camp al...      0
1951  I love this song for two reasons: 1.it is abou...      0
1952                                                wow      0
1953                            Shakira u are so wiredo      0
1954                         Shakira is the best dancer      0

[1955 rows x 2 columns]

In [45]:
data["CLASS"] = data["CLASS"].map({0: "Not Spam",
                                   1: "Spam Comment"})
print(data.sample(5))
data

                                                CONTENT         CLASS
1663  This song is special, because is a song for Af...      Not Spam
1678                                waka waka:-):-):-)      Not Spam
751                              Ah. Good old times (:      Not Spam
1117   are  there  people who like  this shit? hahah...      Not Spam
1502  Please check out my youtube channel! Just uplo...  Spam Comment


<ipython-input-45-fe4aed3f7d4a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["CLASS"] = data["CLASS"].map({0: "Not Spam",


CONTENT         CLASS
0     Huh, anyway check out this you[tube] channel: ...  Spam Comment
1     Hey guys check out my new channel and our firs...  Spam Comment
2                just for test I have to say murdev.com  Spam Comment
3      me shaking my sexy ass on my channel enjoy ^_^   Spam Comment
4               watch?v=vtaRGgvGtWQ   Check this out .  Spam Comment
...                                                 ...           ...
1950  I love this song because we sing it at Camp al...      Not Spam
1951  I love this song for two reasons: 1.it is abou...      Not Spam
1952                                                wow      Not Spam
1953                            Shakira u are so wiredo      Not Spam
1954                         Shakira is the best dancer      Not Spam

[1955 rows x 2 columns]

In [46]:
x = np.array(data["CONTENT"])
y = np.array(data["CLASS"])

In [47]:
cv = CountVectorizer()
x = cv.fit_transform(x)

In [48]:
print(x)

  (0, 2053)	1
  (0, 560)	1
  (0, 951)	1
  (0, 2925)	1
  (0, 3908)	1
  (0, 4383)	1
  (0, 4011)	1
  (0, 935)	1
  (0, 2318)	1
  (1, 951)	1
  (1, 2925)	1
  (1, 3908)	1
  (1, 935)	1
  (1, 1984)	1
  (1, 1895)	1
  (1, 2739)	1
  (1, 2778)	1
  (1, 531)	2
  (1, 2923)	1
  (1, 1652)	1
  (1, 4126)	1
  (1, 2191)	1
  (1, 4078)	1
  (1, 3883)	3
  (1, 2683)	1
  :	:
  (1951, 3908)	1
  (1951, 2191)	1
  (1951, 2120)	1
  (1951, 1682)	1
  (1951, 391)	1
  (1951, 2196)	1
  (1951, 3617)	1
  (1951, 4202)	1
  (1951, 694)	1
  (1951, 2477)	1
  (1951, 4026)	1
  (1951, 3640)	1
  (1951, 796)	1
  (1951, 463)	2
  (1951, 3244)	1
  (1952, 4331)	1
  (1953, 3597)	1
  (1953, 582)	1
  (1953, 3479)	1
  (1953, 4286)	1
  (1954, 2191)	1
  (1954, 3883)	1
  (1954, 724)	1
  (1954, 3479)	1
  (1954, 1189)	1


In [49]:
print(x.shape)

(1955, 4428)


In [50]:
x_array = x.toarray()
print(x_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
print(x_array.shape)

(1955, 4428)


In [52]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.2, 
                                                random_state=42)

model = BernoulliNB()
model.fit(xtrain, ytrain)
print(model.score(xtest, ytest))

0.8618925831202046


In [53]:
sample = "Check this out: https://thecleverprogrammer.com/" 
data = cv.transform([sample]).toarray()
print(model.predict(data))

['Spam Comment']


In [54]:
sample = "Lack of information!" 
data = cv.transform([sample]).toarray()
print(model.predict(data)) 

['Not Spam']


In [55]:
sample = "sfgjsoi isj oigh ws hso http://errtrtrt.com"
data = cv.transform([sample]).toarray()
print(model.predict(data)) 

['Not Spam']
